[package]
name = "starknet_mempool_types"
edition.workspace = true
license.workspace = true
repository.workspace = true
version = "0.0.0"

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
mockall.workspace = true
<<<<<<< HEAD
papyrus_proc_macros = { path = "../papyrus_proc_macros" }
serde = { workspace = true, features = ["derive"] }
starknet_api = { path = "../starknet_api", version = "0.13.0-rc.0" }
starknet_mempool_infra = { path = "../mempool_infra" }
||||||| 40b94928
starknet_api = { path = "../starknet_api", version = "0.13.0-rc.0" }
starknet_mempool_infra = { path = "../mempool_infra" }
=======
starknet_api.workspace = true
starknet_mempool_infra.workspace = true
>>>>>>> origin/main-v0.13.2
thiserror.workspace = true
