[package]
name = "starknet_mempool_types"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
mockall.workspace = true
starknet_api.workspace = true
starknet_api = { path = "../starknet_api", version = "0.14.0-rc.0" }
starknet_mempool_infra.workspace = true
thiserror.workspace = true
