[package]
name = "mempool_node"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
const_format.workspace = true
starknet_gateway = { path = "../gateway", version = "0.4.0-dev.2" }
serde.workspace = true
papyrus_config = { path = "../papyrus_config", version = "0.4.0-dev.2" }
tokio.workspace = true
validator.workspace = true

[dev-dependencies]
assert-json-diff.workspace = true
assert_matches.workspace = true
colored.workspace = true
pretty_assertions.workspace = true
serde_json.workspace = true
mempool_test_utils = {path = "../mempool_test_utils"}
