name: "Setup Cairo Native Dependencies"
description: "Sets up LLVM and GMP libraries"

outputs:
  cairo-native-runtime-library:
    description: "The path to the cairo native runtime library"
    value: ${{ steps.set-env-vars.outputs.cairo-native-runtime-library }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Make script executable
      shell: bash
      run: chmod +x ./scripts/setup_native_deps.sh

    - name: Install Cairo Native Runtime Dependencies
      id: set-env-vars
      shell: bash
      run: ./scripts/setup_native_deps.sh