[package]
name = "starknet_l1_provider"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
indexmap.workspace = true
starknet_api.workspace = true
starknet_l1_provider_types.workspace = true

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
starknet_api = { workspace = true, features = ["testing"] }

[lints]
workspace = true
