[package]
name = "papyrus_protobuf"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
bytes.workspace = true
indexmap.workspace = true
primitive-types.workspace = true
prost.workspace = true
prost-types.workspace = true
starknet_api = { version = "0.12.0-dev.1" }
thiserror.workspace = true

[build-dependencies]
prost-build.workspace = true
