[package]
name = "starknet_mempool"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
derive_more.workspace = true
# TODO(Arni, 1/5/2024): Use a fixed version once the StarkNet API is stable.
starknet_api = { git = "https://github.com/starkware-libs/starknet-api.git", rev = "1b46b42" }
thiserror.workspace = true

[dev-dependencies]
assert_matches.workspace = true
tokio.workspace = true
