[package]
name = "starknet_mempool"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
derive_more.workspace = true
mempool_infra = { path = "../mempool_infra", version = "0.4.0-dev.2"}
# TODO(Arni, 1/5/2024): Use a fixed version once the StarkNet API is stable.
starknet_api = { git = "https://github.com/starkware-libs/starknet-api.git", branch = "main-mempool" }
starknet_mempool_types = { path = "../mempool_types", version = "0.4.0-dev.2"}
tokio.workspace = true

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true
# TODO(Arni, 1/5/2024): Use a fixed version once the StarkNet API is stable.
starknet_api = { git = "https://github.com/starkware-libs/starknet-api.git", branch = "main-mempool", features = ["testing"] }
tokio.workspace = true
