[package]
name = "starknet_sequencer_node"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
testing = ["papyrus_proc_macros", "thiserror"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
const_format.workspace = true
futures.workspace = true
infra_utils.workspace = true
papyrus_config.workspace = true
papyrus_proc_macros = { workspace = true, optional = true }
rstest.workspace = true
serde.workspace = true
starknet_api.workspace = true
starknet_batcher.workspace = true
starknet_batcher_types.workspace = true
starknet_consensus_manager.workspace = true
starknet_gateway.workspace = true
starknet_gateway_types.workspace = true
starknet_http_server.workspace = true
starknet_mempool.workspace = true
starknet_mempool_p2p.workspace = true
starknet_mempool_p2p_types.workspace = true
starknet_mempool_types.workspace = true
starknet_monitoring_endpoint.workspace = true
starknet_sequencer_infra.workspace = true
starknet_sierra_compile.workspace = true
thiserror = { workspace = true, optional = true }
tokio.workspace = true
tracing.workspace = true
validator.workspace = true

[dev-dependencies]
anyhow.workspace = true
assert-json-diff.workspace = true
assert_matches.workspace = true
axum.workspace = true
blockifier.workspace = true
cairo-lang-starknet-classes.workspace = true
colored.workspace = true
futures.workspace = true
indexmap.workspace = true
infra_utils.workspace = true
mempool_test_utils.workspace = true
papyrus_common.workspace = true
papyrus_consensus.workspace = true
papyrus_execution.workspace = true
papyrus_network = { workspace = true, features = ["testing"] }
papyrus_protobuf.workspace = true
papyrus_rpc.workspace = true
papyrus_storage = { workspace = true, features = ["testing"] }
pretty_assertions.workspace = true
reqwest.workspace = true
rstest.workspace = true
serde_json.workspace = true
starknet-types-core.workspace = true
starknet_api.workspace = true
starknet_batcher.workspace = true
starknet_client.workspace = true
starknet_consensus_manager.workspace = true
starknet_gateway = { workspace = true, features = ["testing"] }
starknet_gateway_types.workspace = true
starknet_http_server.workspace = true
starknet_mempool_p2p.workspace = true
starknet_monitoring_endpoint = { workspace = true, features = ["testing"] }
starknet_sequencer_infra = { workspace = true, features = ["testing"] }
starknet_sequencer_node = { workspace = true, features = ["testing"] }
starknet_task_executor.workspace = true
strum.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true
