[package]
name = "papyrus_block_builder"
version = "0.4.0-dev.4"
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "A block-builder for Starknet blocks"

[dependencies]
papyrus_storage = { path = "../../papyrus_storage", version = "0.4.0-dev.4", features = ["testing"] }
starknet_api = { path = "../../starknet_api", version = "0.13.0-dev.9" }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
papyrus_test_utils = { path = "../../papyrus_test_utils" }
