[package]
name = "starknet_mempool_infra"
version = "0.0.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["tokio"]

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
bincode.workspace = true
serde.workspace = true
hyper.workspace = true
papyrus_config = { path = "../papyrus_config", version = "0.4.0-dev.4" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
