[package]
name = "mempool_test_utils"
version = "0.0.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]

[dependencies]
<<<<<<< HEAD
blockifier = { path = "../blockifier", version = "0.8.0-rc.0", features = ["testing"] }
||||||| 40b94928
assert_matches.workspace = true
blockifier = { path = "../blockifier", version = "0.8.0-rc.0", features = ["testing"] }
=======
assert_matches.workspace = true
blockifier = { workspace = true, features = ["testing"] }
>>>>>>> origin/main-v0.13.2
serde_json.workspace = true
starknet-types-core.workspace = true
starknet_api.workspace = true
