name: Blockifier-CI

# TODO(Noa): Delete this workflow once the concurrency feature is deleted.

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled
      - edited
    paths:
      # Other than code-related changes, all changes related to the native-blockifier build-and-push
      # process should trigger the build (e.g., changes to the Dockerfile, build scripts, etc.).
      - '.github/workflows/blockifier_ci.yml'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'crates/blockifier/**'
      - 'scripts/dependencies.sh'
      - 'scripts/sequencer-ci.Dockerfile'

# On PR events, cancel existing CI runs on this same PR for this workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  featureless-build:
    runs-on: starkware-ubuntu-20-04-medium
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap
      - run: cargo build -p blockifier
      - run: cargo test -p blockifier
